name: Greet Everyone
on: [push]

jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: curl -L spectralops.io/get | sudo sh
      - name: Scan
        run: spectral --version && spectral run
