name: Main
on: [push]

jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L spectralops.io/get | sudo sh
      - name: Files
        run: ls -ltr
      - name: Scan
        run: spectral --version && spectral run
